console.clear()
// Repetição 1
console.log('Linha 0')
console.log('Linha 1')
console.log('Linha 2')
console.log('Linha 3')
console.log('Linha 4')
console.log('Linha 5')
console.log('Linha 6')
console.log('Linha 7')
console.log('Linha 8')
console.log('Linha 9')